Grails6 update
alvarosanchez/grails-spring-security-rest pull request #499
Opened 2023-11-27 15:09 UTC by guillermocalvo

2023-11-27 15:45 UTC, alvarosanchez approved these changes

2023-11-28 18:12 UTC, puneetbehl commented
I have left some comments. I would suggest to please try to test plugin by using it in a Grails application.

2023-11-28 18:13 UTC, puneetbehl requested changes

2023-11-28 18:13 UTC, puneetbehl commented on build.gradle
> +            implementation "org.springframework.boot:spring-boot-starter-logging"
I think the scope should be `api` for both `compile` and `provided`.

2023-11-28 18:13 UTC, puneetbehl commented on spring-security-rest/build.gradle
> +    implementation "org.springframework.boot:spring-boot-starter-actuator"
Please look at my previous comment. The scope of dependencies for library/plugin should be `api`.

2023-11-29 17:06 UTC, merged